package visao;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JGerenciarCategoria = new javax.swing.JMenu();
        jMenuCadastroDeCategoria = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuCadastroDeProdutos = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuEntradaEstoque = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuListaDePrecos = new javax.swing.JMenuItem();
        jMenuRelatorioEstoqueMinimo = new javax.swing.JMenuItem();
        jMenuRelatorioEstoqueMaximo = new javax.swing.JMenuItem();
        jMenuBalancoFisicoFinanceiro = new javax.swing.JMenuItem();
        jMenuRelatorioPorCategoria = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        panel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciamento de Estoque");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JGerenciarCategoria.setText("Categoria");

        jMenuCadastroDeCategoria.setText("Cadastro de Categoria");
        jMenuCadastroDeCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroDeCategoriaActionPerformed(evt);
            }
        });
        JGerenciarCategoria.add(jMenuCadastroDeCategoria);

        jMenuBar1.add(JGerenciarCategoria);

        jMenuProdutos.setText("Produtos");

        jMenuCadastroDeProdutos.setText("Cadastro de Produtos");
        jMenuCadastroDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroDeProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuCadastroDeProdutos);

        jMenuBar1.add(jMenuProdutos);

        jMenuEstoque.setText("Estoque");

        jMenuEntradaEstoque.setText("Gerenciador");
        jMenuEntradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEntradaEstoqueActionPerformed(evt);
            }
        });
        jMenuEstoque.add(jMenuEntradaEstoque);

        jMenuBar1.add(jMenuEstoque);

        jMenuRelatorios.setText("Relatórios");

        jMenuListaDePrecos.setText("Lista de Preços");
        jMenuRelatorios.add(jMenuListaDePrecos);

        jMenuRelatorioEstoqueMinimo.setText("Relatório de Estoque Mínimo");
        jMenuRelatorioEstoqueMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioEstoqueMinimoActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelatorioEstoqueMinimo);

        jMenuRelatorioEstoqueMaximo.setText("Relatório de Estoque Máximo");
        jMenuRelatorios.add(jMenuRelatorioEstoqueMaximo);

        jMenuBalancoFisicoFinanceiro.setText("Balanço Físico e Financeiro");
        jMenuBalancoFisicoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBalancoFisicoFinanceiroActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuBalancoFisicoFinanceiro);

        jMenuRelatorioPorCategoria.setText("Relatório por Categoria");
        jMenuRelatorioPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioPorCategoriaActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelatorioPorCategoria);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroDeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroDeCategoriaActionPerformed
        // TODO add your handling code here:
        FrmCadastroDeCategoria objeto = new FrmCadastroDeCategoria();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroDeCategoriaActionPerformed

    private void jMenuRelatorioEstoqueMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioEstoqueMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRelatorioEstoqueMinimoActionPerformed

    private void jMenuBalancoFisicoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBalancoFisicoFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBalancoFisicoFinanceiroActionPerformed

    private void jMenuCadastroDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroDeProdutosActionPerformed
        // TODO add your handling code here:
        FrmTelaDeProdutos objeto = new FrmTelaDeProdutos();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroDeProdutosActionPerformed

    private void jMenuRelatorioPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioPorCategoriaActionPerformed
        // TODO add your handling code here:
        FrmRelatorioQuantidadeProdutosPorCategoria objeto = new FrmRelatorioQuantidadeProdutosPorCategoria();
        objeto.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_jMenuRelatorioPorCategoriaActionPerformed

    private void jMenuEntradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEntradaEstoqueActionPerformed
        FrmGerenciadorEstoque objeto = new FrmGerenciadorEstoque();
        objeto.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jMenuEntradaEstoqueActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JGerenciarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuBalancoFisicoFinanceiro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroDeCategoria;
    private javax.swing.JMenuItem jMenuCadastroDeProdutos;
    private javax.swing.JMenuItem jMenuEntradaEstoque;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuListaDePrecos;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenuItem jMenuRelatorioEstoqueMaximo;
    private javax.swing.JMenuItem jMenuRelatorioEstoqueMinimo;
    private javax.swing.JMenuItem jMenuRelatorioPorCategoria;
    private javax.swing.JMenu jMenuRelatorios;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
